- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mogodb pacakage
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: enabling remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting and enabling mongod
  ansible.builtin.service:
      name: mongod
      state: restarted
      enabled: yes
