- name: app setup
  tags: 
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs setup
  tags: 
  - deployment
  #ansible.builtin.import_role:
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: start user
  tags: 
  - deployment
  ansible.builtin.service:
    name: user
    state: restarted
    enabled: yes